baseURL = "https://ipl-uv.github.io/"
#baseURL = "https://isp.uv.es/github"
publishDir = "public"



#baseURL = "http://127.0.0.1/isp/"
#publishDir = "isp"

languageCode = "en-us"
title = "ISP - Image and Signal Processing group"

theme = "isp_uv"


### configuracion para leer html en archivos .md
[markup.goldmark.renderer]
  unsafe = true

# ////////////////////// Configuración del menú de navegación principal ////////////////////// #

[[menu.main]]
  name = "ISP"
  url = "/"
  weight = 1

[[menu.main]]
  name = "People"
  url = "/people/"
  weight = 2

[[menu.main]]
  name = "Research"
    url = "/research/philosophy/"
  weight = 3
  [[menu.main]]
    parent = "Research"
    name = "Philosophy"
    url = "/research/philosophy/"
    weight = 1
  [[menu.main]]
    parent = "Research"
    name = "Machine learning"
    url = "/research/machine_learning/"
    weight = 2
  [[menu.main]]
    parent = "Research"
    name = "Visual science"
    url = "/research/visual_neuroscience/"
    weight = 3
  [[menu.main]]
    parent = "Research"
    name = "Image processing"
    url = "/research/visual_brain/"
    weight = 4
  [[menu.main]]
    parent = "Research"
    name = "Earth science"
    url = "/research/earth_science/"
    weight = 5
  [[menu.main]]
    parent = "Research"
    name = "Social science"
    url = "/research/social_science"
    weight = 6

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 4

[[menu.main]]
  name = "Facilities"
  url = "/facilities/"
  weight = 5

[[menu.main]]
  name = "Publications"
    url = "/publications/journals/"
  weight = 6
  [[menu.main]]
    parent = "Publications"
    name = "Journals"
    url = "/publications/journals/"
    weight = 1
  [[menu.main]]
    parent = "Publications"
    name = "Conferences"
    url = "/publications/conferences/"
    weight = 2
  [[menu.main]]
    parent = "Publications"
    name = "Books"
    url = "/publications/books/"
    weight = 3
  [[menu.main]]
    parent = "Publications"
    name = "Talks"
    url = "/publications/talks/"
    weight = 4
  [[menu.main]]
    parent = "Publications"
    name = "Technical Reports"
    url = "/publications/technical_reports/"
    weight = 5
  [[menu.main]]
    parent = "Publications"
    name = "Theses"
    url = "/publications/theses/"
    weight = 6

[[menu.main]]
  name = "Code"
  url = "/code/"
  weight = 7
  

[[menu.main]]
  name = "Data"
  url = "/data/"
  weight = 8

[[menu.main]]
  name = "Seminars"
  url = "/seminars/"
  weight = 9

[[menu.main]]
  name = "Courses"
  url = "/courses/"
  weight = 10

[[menu.main]]
  name = "Collaborators"
  url = "/collaborators/"
  weight = 11

[[menu.main]]
  name = "News"
  url = "/news/"
  weight = 12

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 13

[permalinks]
slides = "/ppt/"